# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(212027)
$foreground = rgb(E8DBE1)
$color0 = rgb(47464E)
$color1 = rgb(171530)
$color2 = rgb(1E1B34)
$color3 = rgb(524357)
$color4 = rgb(594C68)
$color5 = rgb(7F6674)
$color6 = rgb(8E717E)
$color7 = rgb(D6C3CB)
$color8 = rgb(95888E)
$color9 = rgb(1F1C3F)
$color10 = rgb(282446)
$color11 = rgb(6E5A74)
$color12 = rgb(77658B)
$color13 = rgb(A9889B)
$color14 = rgb(BD97A8)
$color15 = rgb(D6C3CB)
