# /* ---- Wallust Template Colors ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(3B2B2E)
$foreground = rgb(EBE4DA)
$color0 = rgb(524144)
$color1 = rgb(99666A)
$color2 = rgb(986E6B)
$color3 = rgb(97756D)
$color4 = rgb(967D6E)
$color5 = rgb(948570)
$color6 = rgb(958570)
$color7 = rgb(DAD0C2)
$color8 = rgb(999187)
$color9 = rgb(CC888D)
$color10 = rgb(CB928F)
$color11 = rgb(C99D91)
$color12 = rgb(C8A793)
$color13 = rgb(C6B195)
$color14 = rgb(C6B195)
$color15 = rgb(DAD0C2)
