# /* wallust template - colors-kitty */

foreground         #EBE4DA
background         #3B2B2E
cursor             #DBBBB4

active_tab_foreground     #3B2B2E
active_tab_background     #EBE4DA
inactive_tab_foreground   #EBE4DA
inactive_tab_background   #3B2B2E

active_border_color   #EBE4DA
inactive_border_color #3B2B2E
bell_border_color     #99666A

color0      #524144
color1		#99666A
color2		#986E6B
color3		#97756D
color4		#967D6E
color5		#948570
color6		#958570
color7		#DAD0C2
color8		#999187
color9		#CC888D
color10		#CB928F
color11		#C99D91
color12		#C8A793
color13		#C6B195
color14		#C6B195
color15		#DAD0C2
